apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "2 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: kabisa/docker-postgres-backup:0.1
            envFrom:
              - secretRef:
                  name: postgres-backup-config
            args:
            - postgres_backup
          restartPolicy: OnFailure

# manual start:
# kubectl create job --from=cronjob/postgres-backup backup-test-1